import os
from dotenv import load_dotenv

load_dotenv()

TOKEN = os.getenv("DISCORD_TOKEN")
TICKET_COUNTER_FILE = "ticket_counter.txt"
HELPER_ROLE_ID = os.getenv("HELPER_ROLE_ID")
TICKET_LOG_CHANNEL_ID = os.getenv("TICKET_LOG_CHANNEL_ID")
TICKET_CATEGORY_ID = os.getenv("TICKET_CATEGORY_ID")
TICKET_CHANNEL_ID = os.getenv("TICKET_CHANNEL_ID")
ADMIN_ROLE_ID = os.getenv("ADMIN_ROLE_ID")
LEADERBOARD_CHANNEL_ID = os.getenv("LEADERBOARD_CHANNEL_ID")
WEEKLY_REQUESTER_CAP = os.getenv("WEEKLY_REQUESTER_CAP")
DISCORD_MANAGER_ROLE_ID = os.getenv("DISCORD_MANAGER_ROLE_ID")
OATHSWORN_ROLE_ID = os.getenv("OATHSWORN_ROLE_ID")
HELPER_ROLE_ID = os.getenv("HELPER_ROLE_ID")
